#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Programm Requires Java 21"

LIB_DIR="$SCRIPT_DIR"

CLASSPATH="$LIB_DIR/videoconverter.jar:$LIB_DIR/kotlin-stdlib-1.9.0.jar:$LIB_DIR/kotlinx-serialization-core-jvm-1.9.0.jar:$LIB_DIR/kotlinx-serialization-json-jvm-1.9.0.jar:$LIB_DIR/daras_library-0.1.4-SNAPSHOT.jar"

java -cp "$CLASSPATH" de.shadowdara.videoconverter.MainKt
